### ISSUE TITLE
Creator: support adding header image by url (in addition to upload)

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/Camino#305]
Also:
- let creators add attribution text
- let creators add alt text

**Comment by jxjj** [comment]
Reference it.

Use case:
As a tour creator, I want to use images from elsewhere, say wikipedia or minnesota parks. Currently, I need to download the image from the site and then reupload it to Camino. Not only is this a bit cumbersome, but it encourages copying which invokes copyright that may not fall under fair use. As a creator, I'd be on safer fair use grounds by linking to the source.

Usually Creative Commons assets require attribution. Currently there's no place to put this.

**Comment by cmcfadden** [comment]
I’d be opposed to referencing images - part of our ingest is ensuring the images are a reasonable size and well compressed for mobile connectivity. Opening the door to referencing creates more burdens in that space and makes tours potentially flakey. I think this is mostly something to educate on via our help materials, and encourage folks to be using self-sourced material or otherwise explicitly approved content. Let’s discuss more next week.

**Comment by jxjj** [comment]
Okey doke.
